// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using ClientApi;

namespace SpacetimeDB.Types
{
	[ReducerClass]
	public partial class Reducer { }

	public enum ReducerType
	{
		None,
		SendMessage,
		SetName,
	}

	public partial class ReducerEvent : ReducerEventBase
	{
		public ReducerType Reducer { get; }

		public ReducerEvent(ReducerType reducer, ClientApi.Event dbEvent, object args) : base(dbEvent, args)
		{
			Reducer = reducer;
		}

		public SendMessageArgsStruct SendMessageArgs
		{
			get
			{
				if (Reducer != ReducerType.SendMessage) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "SendMessage");
				return (SendMessageArgsStruct)Args;
			}
		}
		public SetNameArgsStruct SetNameArgs
		{
			get
			{
				if (Reducer != ReducerType.SetName) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "SetName");
				return (SetNameArgsStruct)Args;
			}
		}

		public object[] GetArgsAsObjectArray()
		{
			switch (Reducer)
			{
				case ReducerType.SendMessage:
				{
					var args = SendMessageArgs;
					return new object[] {
						args.Text,
					};
				}
				case ReducerType.SetName:
				{
					var args = SetNameArgs;
					return new object[] {
						args.Name,
					};
				}
				default: throw new System.Exception($"Unhandled reducer case: {Reducer}. Please run SpacetimeDB code generator");
			}
		}
	}
}
