// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using ClientApi;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	public partial class SendMessageArgsStruct
	{
		public string Text;
	}

	public static partial class Reducer
	{
		public delegate void SendMessageHandler(ReducerEvent reducerEvent, string text);
		public static event SendMessageHandler? OnSendMessageEvent;

		public static void SendMessage(string text)
		{
			SpacetimeDBClient.instance.InternalCallReducer("send_message", new SendMessageArgsStruct { Text = text });
		}

		[ReducerCallback(FunctionName = "send_message")]
		public static bool OnSendMessage(ClientApi.Event dbEvent)
		{
			if (OnSendMessageEvent == null) return false;
			var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).SendMessageArgs;
			OnSendMessageEvent(
				(ReducerEvent)dbEvent.FunctionCall.CallInfo,
				args.Text
			);
			return true;
		}

		[DeserializeEvent(FunctionName = "send_message")]
		public static void SendMessageDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(
				ReducerType.SendMessage,
				dbEvent,
				BSATNHelpers.FromProtoBytes<SendMessageArgsStruct>(dbEvent.FunctionCall.ArgBytes)
			);
		}
	}

}
