// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using ClientApi;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	public partial class SetNameArgsStruct
	{
		public string Name;
	}

	public static partial class Reducer
	{
		public delegate void SetNameHandler(ReducerEvent reducerEvent, string name);
		public static event SetNameHandler? OnSetNameEvent;

		public static void SetName(string name)
		{
			SpacetimeDBClient.instance.InternalCallReducer("set_name", new SetNameArgsStruct { Name = name });
		}

		[ReducerCallback(FunctionName = "set_name")]
		public static bool OnSetName(ClientApi.Event dbEvent)
		{
			if (OnSetNameEvent == null) return false;
			var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).SetNameArgs;
			OnSetNameEvent(
				(ReducerEvent)dbEvent.FunctionCall.CallInfo,
				args.Name
			);
			return true;
		}

		[DeserializeEvent(FunctionName = "set_name")]
		public static void SetNameDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(
				ReducerType.SetName,
				dbEvent,
				BSATNHelpers.FromProtoBytes<SetNameArgsStruct>(dbEvent.FunctionCall.ArgBytes)
			);
		}
	}

}
